# ──────────────────────────────────────
# Frontend
# ──────────────────────────────────────
frontend:
  deploymentName: shopverse-frontend
  replicas: 2
  image: "295493126166.dkr.ecr.ap-south-1.amazonaws.com/shopverse-frontend:60d2479331d9c4d675ac4db6c93503834d456230" # frontend-image
  imagePullSecrets: []
  serviceName: shopverse-frontend-svc
  servicePort: 80
  ingressName: shopverse-frontend-ingress
  ingressHost: shopverse.gangadevops.site
  ingressClassName: traefik
# ──────────────────────────────────────
# Backend
# ──────────────────────────────────────
backend:
  deploymentName: shopverse-backend
  replicas: 2
  image: "295493126166.dkr.ecr.ap-south-1.amazonaws.com/shopverse-backend:60d2479331d9c4d675ac4db6c93503834d456230" # backend-image
  imagePullSecrets: []
  serviceName: shopverse-backend-svc
  servicePort: 8080
  ingressName: shopverse-backend-ingress
  ingressHost: shopverse-api.gangadevops.site
  ingressClassName: traefik   # <-- add this
# ──────────────────────────────────────
# MySQL
# ──────────────────────────────────────
mysql:
  database: shopverse
  user: shopverse
  rootPassword: "R00tPass!9x74"
  password: "ShopUser#4kLm4"
  storage: 5Gi
  storageClass: gp2
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"
# ──────────────────────────────────────
# Shared
# ──────────────────────────────────────
ingress:
  enabled: false
  ingressClassName: traefik
  annotations: {}
jwtSecret: "JWTs3cr3t!8zYpQw"
