# ──────────────────────────────────────
# Frontend
# ──────────────────────────────────────
frontend:
  deploymentName: shopverse-frontend
  replicas: 2
  image: "295493126166.dkr.ecr.ap-south-1.amazonaws.com/shopverse-frontend:5c926d322df4b915e04e91e495bd52c42c2beff6" # frontend-image
  imagePullSecrets: []
  serviceName: shopverse-frontend-svc
  servicePort: 80
  ingressName: shopverse-frontend-ingress
  ingressHost: ""
# ──────────────────────────────────────
# Backend
# ──────────────────────────────────────
backend:
  deploymentName: shopverse-backend
  replicas: 2
  image: "295493126166.dkr.ecr.ap-south-1.amazonaws.com/shopverse-backend:5c926d322df4b915e04e91e495bd52c42c2beff6" # backend-image
  imagePullSecrets: []
  serviceName: shopverse-backend-svc
  servicePort: 8080
  ingressName: shopverse-backend-ingress
  ingressHost: ""
# ──────────────────────────────────────
# MySQL
# ──────────────────────────────────────
mysql:
  database: shopverse
  user: shopverse
  rootPassword: "R00tPass!9x74"
  password: "ShopUser#4kLm4"
  storage: 5Gi
  storageClass: gp2
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"
# ──────────────────────────────────────
# Shared
# ──────────────────────────────────────
ingress:
  enabled: false
  ingressClassName: traefik
  annotations: {}
jwtSecret: "JWTs3cr3t!8zYpQw"
