name: ShopVerse CI/CD

on:
  push:
    branches:
      - main

jobs:

  # ======================================================
  # Stage 1 : Test
  #
  # Purpose:
  # Verify that both frontend and backend code are healthy
  # before proceeding to the next CI stages.
  #
  # This stage performs:
  # 1. Checkout source code
  # 2. Setup Go environment
  # 3. Download Go dependencies
  # 4. Run backend unit tests
  # 5. Setup Node.js
  # 6. Install frontend dependencies
  # 7. Run ESLint for frontend code quality
  #
  # If any step fails, the pipeline stops here.
  # ======================================================

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:

      # Checkout latest source code
      - uses: actions/checkout@v4

      # Install Go runtime
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      # Download backend dependencies
      - name: Update go.sum
        working-directory: ./backend
        run: go mod tidy

      # Run backend unit tests
      - name: Run Go tests
        working-directory: ./backend
        run: go test ./...

      # Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # Install frontend dependencies
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      # Run ESLint
      - name: Run frontend lint
        working-directory: ./frontend
        run: npx eslint . --ext js,jsx --report-unused-disable-directives --max-warnings 0 --config .eslintrc.cjs
